export const PRODUCT_BY_ID_GET_REQUEST = "PRODUCT_BY_ID_GET_REQUEST";
export const PRODUCT_BY_ID_GET_SUCCESS = "PRODUCT_BY_ID_GET_SUCCESS";
export const PRODUCT_BY_ID_GET_FAIL = "PRODUCT_BY_ID_GET_FAIL";
export const ITEMS_GET_REQUEST = "ITEMS_GET_REQUEST";
export const ITEMS_GET_SUCCESS = "ITEMS_GET_SUCCESS";
export const ITEMS_GET_FAIL = "ITEMS_GET_FAIL";
