export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const EMPTY_BASKET = "EMPTY_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const BASKET_DB_GET_REQUEST = "BASKET_DB_GET_REQUEST";
export const BASKET_DB_GET_SUCCESS = "BASKET_DB_GET_SUCCESS";
export const BASKET_DB_GET_FAIL="BASKET_DB_GET_FAIL";
export const ORDERS_HISTORY_GET_REQUEST="ORDERS_HISTORY_GET_REQUEST"
export const ORDERS_HISTORY_GET_SUCCESS="ORDERS_HISTORY_GET_SUCCESS"
export const ORDERS_HISTORY_GET_FAIL="ORDERS_HISTORY_GET_FAIL"

export const ITEMS_ADD_REQUEST = "ITEMS_ADD_REQUEST";
export const ITEMS_ADD_SUCCESS = "ITEMS_ADD_SUCCESS";
export const ITEMS_ADD_FAIL = "ITEMS_ADD_FAIL";
export const ITEMS_UPDATE_REQUEST = "ITEMS_UPDATE_REQUEST";
export const ITEMS_UPDATE_SUCCESS = "ITEMS_UPDATE_SUCCESS";
export const ITEMS_UPDATE_FAIL = "ITEMS_UPDATE_FAIL";
export const ITEMS_DELETE_REQUEST = "ITEMS_DELETE_REQUEST";
export const ITEMS_DELETE_SUCCESS = "ITEMS_DELETE_SUCCESS";
export const ITEMS_DELETE_FAIL = "ITEMS_DELETE_FAIL";

export const SUMMARY_OF_ORDER_REQUEST = "SUMMARY_OF_ORDER_REQUEST";
export const SUMMARY_OF_ORDER_SUCCESS = "SUMMARY_OF_ORDER_SUCCESS";
export const SUMMARY_OF_ORDER_FAIL = "SUMMARY_OF_ORDER_FAIL";

export const SINGLE_ORDER_HISTORY_REQUEST="SINGLE_ORDER_HISTORY_REQUEST";
export const SINGLE_ORDER_HISTORY_SUCCESS="SINGLE_ORDER_HISTORY_SUCCESS";
export const SINGLE_ORDER_HISTORY_FAIL="SINGLE_ORDER_HISTORY_FAIL";