export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const EMPTY_BASKET = "EMPTY_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";

export const ITEMS_GET_REQUEST = "ITEMS_GET_REQUEST";
export const ITEMS_GET_SUCCESS = "ITEMS_GET_SUCCESS";
export const ITEMS_GET_FAIL = "ITEMS_GET_FAIL";

export const ITEMS_ADD_REQUEST = "ITEMS_ADD_REQUEST";
export const ITEMS_ADD_SUCCESS = "ITEMS_ADD_SUCCESS";
export const ITEMS_ADD_FAIL = "ITEMS_ADD_FAIL";
export const ITEMS_UPDATE_REQUEST = "ITEMS_UPDATE_REQUEST";
export const ITEMS_UPDATE_SUCCESS = "ITEMS_UPDATE_SUCCESS";
export const ITEMS_UPDATE_FAIL = "ITEMS_UPDATE_FAIL";
export const ITEMS_DELETE_REQUEST = "ITEMS_DELETE_REQUEST";
export const ITEMS_DELETE_SUCCESS = "ITEMS_DELETE_SUCCESS";
export const ITEMS_DELETE_FAIL = "ITEMS_DELETE_FAIL";

export const PRODUCT_BY_ID_GET_REQUEST = "PRODUCT_BY_ID_GET_REQUEST";
export const PRODUCT_BY_ID_GET_SUCCESS = "PRODUCT_BY_ID_GET_SUCCESS";
export const PRODUCT_BY_ID_GET_FAIL = "PRODUCT_BY_ID_GET_FAIL";

export const SUMMARY_OF_ORDER_REQUEST = "SUMMARY_OF_ORDER_REQUEST";
export const SUMMARY_OF_ORDER_SUCCESS = "SUMMARY_OF_ORDER_SUCCESS";
export const SUMMARY_OF_ORDER_FAIL = "SUMMARY_OF_ORDER_FAIL";
