export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const EMPTY_BASKET = "EMPTY_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";


export const Items_GET_REQUEST = "Items_GET_REQUEST";
export const Items_GET_SUCCESS = "Items_GET_SUCCESS";
export const Items_GET_FAIL = "Items_GET_FAIL";

export const PRODUCT_BY_ID_GET_REQUEST='PRODUCT_BY_ID_GET_REQUEST';
export const PRODUCT_BY_ID_GET_SUCCESS="PRODUCT_BY_ID_GET_SUCCESS";
export const PRODUCT_BY_ID_GET_FAIL="PRODUCT_BY_ID_GET_FAIL";

export const SUMMARY_OF_ORDER_REQUEST='SUMMARY_OF_ORDER_REQUEST'
export const SUMMARY_OF_ORDER_SUCCESS='SUMMARY_OF_ORDER_SUCCESS'
export const SUMMARY_OF_ORDER_FAIL='SUMMARY_OF_ORDER_FAIL'
